import {useEffect,useState} from 'react';
import {useAuth} from '../auth';
import {BookingList,ErrorNotice,money} from '../components';
export default function Dashboard(){
 const {api}=useAuth();const [gigs,setGigs]=useState([]);const [bookings,setBookings]=useState([]);const [income,setIncome]=useState({totalIncome:0,completedBookings:0});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [editing,setEditing]=useState(null);const [deleting,setDeleting]=useState(null);const [revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);Promise.all([api('/gigs/mine',{signal:c.signal}),api('/bookings/freelancer',{signal:c.signal}),api('/income',{signal:c.signal})]).then(([g,b,i])=>{setGigs(g.gigs);setBookings(b.bookings);setIncome(i);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[api,revision]);
 async function save(e){e.preventDefault();if(busy)return;const form=e.currentTarget;const values=new FormData(form);const body={title:values.get('title').trim(),description:values.get('description').trim(),price:Number(values.get('price')),category:values.get('category').trim()};if(!body.title||!body.description||!Number.isFinite(body.price)||body.price<0){setError('Enter a title, description and a valid non-negative price.');return;}if(editing)body.isActive=values.get('active')==='on';setBusy(true);setError('');setNotice('');try{await api(editing?`/gigs/${editing._id}`:'/gigs',{method:editing?'PUT':'POST',body});setNotice(editing?'Gig updated.':'Gig created.');setEditing(null);form.reset();setRevision(r=>r+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function remove(){if(busy)return;setBusy(true);setError('');try{await api(`/gigs/${deleting._id}`,{method:'DELETE'});setDeleting(null);setNotice('Gig deleted.');setRevision(r=>r+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><div className="section-head"><div><span className="eyebrow">Your freelance workspace</span><h1>Freelancer dashboard</h1></div><button className="secondary" onClick={()=>{setError('');setRevision(r=>r+1);}} disabled={loading}>Refresh</button></div><ErrorNotice message={error}/>{notice&&<p role="status" className="notice">{notice}</p>}{loading?<p role="status">Loading dashboard…</p>:<div className="stats"><div className="card"><span>Total income</span><strong>{money(income.totalIncome)}</strong></div><div className="card"><span>Completed transactions</span><strong>{income.completedBookings}</strong></div><div className="card"><span>Your gigs</span><strong>{gigs.length}</strong></div></div>}
 <section className="panel"><h2>{editing?'Edit your gig':'Create a gig'}</h2><form key={editing?._id||'new'} onSubmit={save}><label>Title<input name="title" required maxLength={120} defaultValue={editing?.title||''}/></label><label>Description<textarea name="description" required maxLength={2000} rows={4} defaultValue={editing?.description||''}/></label><div className="form-row"><label>Price (ZAR)<input name="price" type="number" required min="0" step="0.01" defaultValue={editing?.price??''}/></label><label>Category<input name="category" maxLength={50} defaultValue={editing?.category||''}/></label></div>{editing&&<label className="checkbox"><input type="checkbox" name="active" defaultChecked={editing.isActive}/>Available for booking</label>}<div className="actions"><button disabled={busy}>{busy?'Saving…':editing?'Save changes':'Create gig'}</button>{editing&&<button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel editing</button>}</div></form></section>
 <section className="panel"><h2>Your gigs</h2>{!gigs.length?<p className="empty">Create your first gig above.</p>:gigs.map(g=><article className="own-gig" key={g._id}><div><h3>{g.title}</h3><p>{money(g.price)} · {g.isActive?'Active':'Inactive'}</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>{setEditing(g);setError('');}}>Edit</button><button className="danger" disabled={busy} onClick={()=>setDeleting(g)}>Delete</button></div></article>)}</section>
 {deleting&&<section className="notice" aria-label="Confirm gig deletion"><h2>Delete “{deleting.title}”?</h2><p>This cannot be undone.</p><div className="actions"><button className="danger" onClick={remove} disabled={busy}>Confirm delete</button><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>Cancel</button></div></section>}
 <section className="panel"><h2>Bookings for your services</h2><BookingList bookings={bookings} freelancer/></section></>;
}
